spring:
  datasource:
    hikari:
      maximum-pool-size: 100
      connection-timeout: 1000
  profiles:
    include: data
mybatis:
  type-aliases-package: com.kert.compute.pojo
  mapper-locations: classpath:mapper\*.xml

