spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 1111
    url: jdbc:sqlserver://127.0.0.1;database=tsst;trustServerCertificate=true